kwc = '''
无人艇,水面无人艇,水下无人潜航器,水下航行器,水下无人机器人,集群,可潜无人艇,半潜无人艇,武装察打一体无人艇,
有人无人协同,作战概念,作战场景,作战运用,探障,破障,柔性障碍,海底地形建模,水下战场情报,监视和侦察,反水雷战,
反潜战,海床绘图,自主航行,自主技术,智能无人,路径规划,导航,避碰,任务分配,目标识别,视觉感知,
通迅,水下通迅,超视距控制,无人艇布放,无人潜航器回收,续航力,动力装置,推进器,非声探测,水下特种作战,
反无人装备与技术,无人运输,作战支援,抗登陆
'''

kw1 = '''
Unmanned boats, surface unmanned boats, underwater unmanned submersibles, underwater vehicles, u
nderwater unmanned robots, clusters, submersible unmanned boats, semi-submersible unmanned boats, 
armed reconnaissance and strike unmanned boats, manned and unmanned coordination, combat concepts, 
combat scenarios, combat applications, obstacle detection, obstacle removal, flexible obstacles, 
seabed terrain modeling, underwater battlefield intelligence, surveillance and reconnaissance, 
anti-mine warfare, anti-submarine warfare, seabed mapping, autonomous navigation, autonomous technology, 
intelligent unmanned, path planning, navigation, collision avoidance, task allocation, target recognition, 
visual perception, communication, underwater communication, beyond-visual-range control, 
unmanned boat deployment, unmanned submersible vehicle recovery, endurance, power plant, 
propulsion, non-acoustic detection, underwater special operations, anti-unmanned equipment and technology, 
unmanned transportation, combat support, anti-landing
'''

kw2 = '''
Unmanned Surface Vessels (USVs),
Autonomous Underwater Vehicles (AUVs),
Remotely Operated Underwater Vehicles (ROVs),
Underwater Robotics,
Swarm Technology,
Semi-submersible Drones,
Armed Reconnaissance and Strike USVs,
Manned-Unmanned Teaming (MUM-T),
Combat Doctrine,
Operational Scenarios,
Tactical Applications,
Obstacle Detection and Avoidance Systems,
Mine Countermeasures (MCM),
Flexible Obstacle Removal,
Seabed Terrain Mapping,
Underwater Intelligence, Surveillance, and Reconnaissance (ISR),
Anti-Submarine Warfare (ASW),
Bathymetric Mapping,
Autonomous Navigation Systems,
Artificial Intelligence in Maritime Systems,
Path Planning Algorithms,
Collision Avoidance Systems,
Task Allocation and Mission Planning,
Target Recognition and Classification,
Computer Vision for Maritime Applications,
Underwater Communication Systems,
Beyond Line-of-Sight (BLOS) Control,
Unmanned Vehicle Deployment and Recovery Systems,
Long-Endurance Maritime Systems,
Marine Propulsion Technologies,
Non-Acoustic Detection Methods,
Special Underwater Operations,
Counter-Unmanned Systems (C-UxS),
Autonomous Logistics and Transportation,
Combat Support Systems,
Anti-Amphibious Landing Defenses,
'''

kw2b_en = '''
Unmanned Surface Vessels ,
Autonomous Underwater Vehicles,
Remotely Operated Underwater Vehicles,
Underwater Robotics,
Swarm Technology,
Semi-submersible Drones,
Armed Reconnaissance and Strike USVs,
Manned-Unmanned Teaming,
Combat Doctrine,
Operational Scenarios,
Tactical Applications,
Obstacle Detection and Avoidance Systems,
Mine Countermeasures,
Flexible Obstacle Removal,
Seabed Terrain Mapping,
Underwater Intelligence, Surveillance, and Reconnaissance,
Anti-Submarine Warfare,
Bathymetric Mapping,
Autonomous Navigation Systems,
Artificial Intelligence in Maritime Systems,
Path Planning Algorithms,
Collision Avoidance Systems,
Task Allocation and Mission Planning,
Target Recognition and Classification,
Computer Vision for Maritime Applications,
Underwater Communication Systems,
Beyond Line-of-Sight Control,
Unmanned Vehicle Deployment and Recovery Systems,
Long-Endurance Maritime Systems,
Marine Propulsion Technologies,
Non-Acoustic Detection Methods,
Special Underwater Operations,
Counter-Unmanned Systems,
Autonomous Logistics and Transportation,
Combat Support Systems,
Anti-Amphibious Landing Defenses,
'''

kw2b_fr='''
Navires de surface sans pilote,
Véhicules sous-marins autonomes,
Véhicules sous-marins télécommandés,
Robotique sous-marine,
Technologie d'essaim,
Drones semi-submersibles,
USV armés de reconnaissance et de frappe,
Teaming avec et sans pilote,
Doctrine de combat,
Scénarios opérationnels,
Applications tactiques,
Systèmes de détection et d'évitement d'obstacles,
Lutte contre les mines,
Suppression flexible des obstacles,
Cartographie du terrain des fonds marins,
Intelligence, surveillance et reconnaissance sous-marines,
Guerre anti-sous-marine,
Cartographie bathymétrique,
Systèmes de navigation autonomes,
Intelligence artificielle dans les systèmes maritimes,
Algorithmes de planification de chemin,
Systèmes anticollision,
Répartition des tâches et planification des missions,
Reconnaissance et classification des cibles,
Vision par ordinateur pour les applications maritimes,
Systèmes de communication sous-marine,
Au-delà du contrôle de la ligne de vue,
Systèmes de déploiement et de récupération de véhicules sans pilote,
Systèmes Maritimes Longue Endurance,
Technologies de propulsion marine,
Méthodes de détection non acoustiques,
Opérations sous-marines spéciales,
Systèmes anti-sans pilote,
Logistique et transport autonomes,
Systèmes de soutien au combat,
Défenses anti-atterrissage amphibies,
'''

kw2b_jp='''
無人水上艦艇,
自律型水中車両,
遠隔操作型水中車両,
水中ロボット工学,
スウォームテクノロジー,
半潜水型ドローン,
武装偵察・攻撃型USV,
有人無人チーム,
戦闘教義,
作戦シナリオ,
戦術的応用,
障害物検知・回避システム,
機雷対策,
柔軟な障害物除去,
海底地形マッピング,
水中情報収集・監視・偵察,
対潜水艦戦,
水深マッピング,
自律航行システム,
海事システムにおける人工知能,
経路計画アルゴリズム,
衝突回避システム,
タスク割り当て・ミッション計画,
ターゲット認識・分類,
海事用コンピュータービジョンアプリケーション,
水中通信システム,
視線外制御,
無人機展開・回収システム,
長時間航行可能な海洋システム,
海洋推進技術,
非音響探知方法,
特殊水中作戦,
対無人システム,
自律ロジスティクスおよび輸送,
戦闘支援システム,
対水陸両用上陸防御,
'''

kw2b_ge='''
Unbemannte Überwasserschiffe,
Autonome Unterwasserfahrzeuge,
Ferngesteuerte Unterwasserfahrzeuge,
Unterwasserrobotik,
Schwarmtechnologie,
Halbtauchfähige Drohnen,
Bewaffnete Aufklärungs- und Angriffs-USVs,
Bemannte-unbemannte Teamarbeit,
Kampfdoktrin,
Einsatzszenarien,
Taktische Anwendungen,
Hinderniserkennungs- und -vermeidungssysteme,
Minenabwehrmaßnahmen,
Flexible Hindernisbeseitigung,
Kartierung des Meeresbodens,
Unterwasseraufklärung, -überwachung und -aufklärung,
U-Boot-Abwehr,
Bathymetrische Kartierung,
Autonome Navigationssysteme,
Künstliche Intelligenz in maritimen Systemen,
Pfadplanungsalgorithmen,
Kollisionsvermeidungssysteme,
Aufgabenzuweisung und Einsatzplanung,
Zielerkennung und -klassifizierung,
Computer Vision für maritime Anwendungen,
Unterwasserkommunikationssysteme,
Außerhalb der Sichtlinie Steuerung,
Systeme zum Einsatz und zur Bergung unbemannter Fahrzeuge,
Langstrecken-Schiffssysteme,
Schiffsantriebstechnologien,
Nichtakustische Erkennungsmethoden,
Spezielle Unterwasseroperationen,
Abwehr unbemannter Systeme,
Autonome Logistik und Transport,
Kampfunterstützungssysteme,
Abwehr amphibischer Landesysteme,
'''


achievment ={"en":"achievement","ge":"Vollbringung","fr":"réalisation","jp":"成果"}
news ={"en":"news","jp":"ニュース","fr":"nouvelles","ge":"Nachricht"}